server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    index index.html;

    location /todo-list/ {
        try_files $uri $uri/ /todo-list/index.html;
    }

    location /todo-node/ {
        proxy_pass http://todo-node:3000/;
    }
}